### ISSUE TITLE
Disk vs volume/partition

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xStorage#3]
I am a bit confused here. The xDisk resource takes a DiskNumber and a DriveLetter parameter, but one never assigns a drive letter to a disk, but to a partition.

In the code it is assumed that each disk only has one partition.

If multiple partitions (volumes) exists on a disk, the configuration doesn't change the drive letter but doesn't throw an error. 

Also what if I want to assign a drive letter to the second partition on disk 2, I can't do that.

Finally running the configuration, some verbose output claims:

> A reboot is required to progress further. Please reboot the system.

I don't know where that comes from but it is not true.

**Comment by msperrin** [comment]
The resource actually sets a reboot as part of Set-TargetResource and the node will reboot after each disk is processed if RebootNodeifneeded = $true in the LCM config.
  
76  $global:DSCMachineStatus = 1    

Not sure why there is a need to reboot after formatting a disk but I would suggest this should be removed and to allow XpendingReboot to handle any reboots that get set. (Unless the author had a good reason for doing this?).

**Comment by KarolKaczmarek** [comment]
I believe your concerns are addressed by #4 
Please take a look and add comments to the PR if you have some additional feedback.
Thanks!

**Comment by hahndorf** [comment]
Ok, I see.
I can also see the same pull request removes:

     $global:DSCMachineStatus = 1  

so both my issues are already worked on.

**Comment by mgreenegit** [comment]
Hello.  I was one of the original contributors to the resource.  During testing, we needed data disks to be configured and then guarantee they would be available as soon as possible for a service installation.  Across different environments, we would occasionally see errors where the volume was not yet available for the next resource to utilize and the configuration would fail.  The best way to reduce the error rate to 0 was to reboot the node before continuing, since looping until the disk was available would often take longer than the reboot  (no additional diagnostic was performed).  If that issue is not occurring at large then I see no reason to leave the reboot.  Another approach would be to make it an optional property.
