### ISSUE TITLE
Set DriveLetter as key for xMountImage and remove Name

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xStorage#56]
The xMountImage resource is defined in a way that it can easily cause invalid configurations.

The Name parameter is the current Key and should not be required or used at all. It should be removed completely.

The DriveLetter parameter should be set as the Key for this resource. This will prevent invalid configurations (where a two different images are mounted to the same drive).

The ImagePath parameter should be a required parameter.

I'd propose the MOF:

```
[ClassVersion("1.0.0.0"), FriendlyName("xMountImage")]
class MSFT_xMountImage : OMI_BaseResource
{
    [Required, Description("Specifies the path of the VHD or ISO file")] String ImagePath;
    [Key, Description("Specifies the drive letter after the ISO is mounted")] String DriveLetter;
    [Write, Description("Determines whether the setting should be applied or removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
```

I realize this is a breaking change, but I think this needs to be done because:
1. the resource is broken in it's current state
2. there are several bugs in the current resource that prevent it from being used in many cases (basic unit and integration tests would have picked these problems up).

I'm currently working on bringing this resource module up to HQRM standards but I think this needs to be fixed at the same time.

@TravisEz13 - what do you reckon?

**Comment by TravisEz13** [comment]
@PlagueHO 
Images cannot be mounted to mount points?
Can images be mounted to multiple drive letters?

Do we want to support either of these cases?

**Comment by PlagueHO** [comment]
@TravisEz13 - good points.

1. ISO Images can't be assigned to folder mount point (like disk volumes can be) - but as far as I can tell, only via the UI (Disk Management allows it). I haven't been able to manage this via PS. The ```Add-PartitionAccessPath``` cmdlet only supports mounting partitions on disks to folders - not DiskImages themselves.

But if there is a method then it would be great to expose it.

2. Technically yes, this is something that could be done in the real world. Not sure I can think of a scenario though. That said, I see no reason to not support it.

Perhaps this MOF:
```powershell
[ClassVersion("1.0.0.0"), FriendlyName("xMountImage")]
class MSFT_xMountImage : OMI_BaseResource
{
    [Key, Description("Specifies the path of the VHD or ISO file")] String ImagePath;
    [Key, Description("Specifies the drive letter after the ISO is mounted")] String DriveLetter;
    [Write, Description("Determines whether the setting should be applied or removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
```

This would allow scenario 2, but not scenario 1. What I would suggest though is a separate resource entirely for Scenario 1 if we can find a way of doing it.

There is a request in place for mounting physical disks to folders (https://github.com/PowerShell/xStorage/issues/47), and it has been proposed that instead of extending xDisk we should create a new resource for this. So I'd say we'd want to keep the design patterns the same.

**Comment by TravisEz13** [comment]
@PlagueHO, One scenario I see that would be difficult to support with that is

> I don't want C:\image.iso mounted anywhere.

It might be better to make `driveletter` an array (and therefore not a key) and you must specify all mount points in one resource.... also ... not great.

**Comment by PlagueHO** [comment]
@TravisEz13 hmm. I think your suggestion could actually be workable.

We'd have two possible MOF formats:
1. 
```powershell
[ClassVersion("1.0.0.0"), FriendlyName("xMountImage")]
class MSFT_xMountImage : OMI_BaseResource
{
    [Key, Description("Specifies the path of the VHD or ISO file")] String ImagePath;
    [Write, Description("Specifies the drive letter after the ISO is mounted")] String DriveLetter[];
    [Write, Description("Determines whether the setting should be applied or removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
```
The resource would need a check to validate that at least one drive letter was set if Ensure was "present", but none were set if Ensure was "Absent".

2.
```powershell
[ClassVersion("1.0.0.0"), FriendlyName("xMountImage")]
class MSFT_xMountImage : OMI_BaseResource
{
    [Key, Description("Specifies the path of the VHD or ISO file")] String ImagePath;
    [Write, Description("Specifies the drive letter after the ISO is mounted")] String DriveLetter[];
};
```
That one would dismount the image from all drives IF DriveLetter was an empty array. Otherwise it would mount the image to the listed drives.

I'm don't think either solution is perfect though.

**Comment by TravisEz13** [comment]
I like option 1 better, but I think either are viable.        I think 1 because I think it's more obvious how to dismount.... maybe the values in the value map  could be clarified a bit.

**Comment by PlagueHO** [comment]
Cool. Ok, I'll give it a couple more days and if there are no further comments I'll include option 1 with #53.

**Comment by PlagueHO** [comment]
Working on the changes to this one now.

**Comment by PlagueHO** [comment]
@TravisEz13 - unfortunately I've run into a limitation with the *-DiskImage cmdlets that isn't going to allow support for mounting an ISO (or VHD) multiple times.

I can mount the same ISO twice using the following code:
![2016-09-10_16-54-39](https://cloud.githubusercontent.com/assets/7589164/18408055/516969fa-7777-11e6-8823-934245e1267d.png)

But as you can see, piping ```Get-DiskImage``` to ```Get-Volume``` only shows the first volume. I can't find a way to connect the second volume to the DiskImage itself or get the DiskImage object for the second device (there must be one). And I also can't find a way to only dismount a specific DiskImage volume - it will always Dismount the most recent copy of the image that was mounted.

I've tried working through WMI and CIM and just can't make it work.

Do you have any thoughts on how I might solve this? If not, we might need to go back to the original design - minus the 'Name' parameter of course (because it incorrectly gave the impression you could mount the same image twice, when you couldn't and would end up in a real mess if you tried).

I'll hold off on making any further changes to my fork till I hear back from you.

**Comment by PlagueHO** [comment]
@TravisEz13 - I haven't been able to find anyway around the problems above. So I think I'll go with the original plan and just remove the "Name" parameter as it was redundant and actually caused more problems.

Also, after thinking about it, it would not actually make sense to allow a VHD disk image to be mounted twice.

I'm also going to enable proper support for VHD/VHDx mounting as a Read-only or Read/Write disk because I don't think it makes sense to exclude the functions.

If there are no objections?

**Comment by TravisEz13** [comment]
No objections

**Comment by Peter-B-Clark** [comment]
Hi, I'm not sure whether to open a new bug or reopen this one. This is my first contribution to GitHub, so please be gentle!
This has broken things for us - we ensure an ISO mount is present on a drive letter, then do some stuff with it and later in the same MOF, with a dependency on the intervening tasks being completed, ensure that it is absent. This used to work (in 2.6.0.0) by using different names for the mount and dismount process, but now it refuses to generate the MOF because it says we're trying to both mount and dismount the same ISO. Are we getting it wrong?
We've wound up using a script resource to unmount the ISO, but we should be able to use xStorage.
Do you need error messages or example scripts, or is the issue clear from the description above?

**Comment by PlagueHO** [comment]
Hi @Peter-B-Clark - glad to have your comments on this! Thank you for posting :grin:

I think I understand. The problem here is that you are actually exploiting an unintended behavior of this resource.

DSC is designed to define the desired state a node should be in at the end of config processing. In this case you're defining two conflicting states of the mounted ISO and exploiting the fact that you could do this :grin: . DSC resources are supposed to prevent this - because if you ever reported on if this machine were in state it would report that it was, but then would still apply changes.

In your case this behavior is desirable, but it goes against the intent of DSC (and the rules of how resources should behave).

So, my question: Is it critical that you dismount the ISO at the end of the config? I can understand why you might want to do this from a "nice clean machine without a disk inserted" standpoint, but is it critical to the node state and behavior?

**Comment by Peter-B-Clark** [comment]
Thanks for your response!
The issue we have with leaving the ISO mounted is that it's one we occasionally update, and we can't replace the file if 30 VMs still have it mounted. Your explanation does make sense, but we need to, for example, update the slipstreamed CU on a SharePoint installation iso. We don't want to provision lots of extra space on the VMs to temporarily copy the all the files locally, and there are issues with referring to remote shares to install the files.
Temporarily mounting an ISO as part of a DSC process is a useful workaround, but if a properly behaving DSC resource wouldn't permit that, then we'll continue to use the script resource workaround rather than ask you to break your compliance for our convenience!

**Comment by Peter-B-Clark** [comment]
Thanks for your response! It sounds like we've been misusing DSC and that was only possible because of a bug that has now been fixed, but I'll explain anyway, to make sure I'm right about that.

We mount ISOs to install software on systems without having to install from a share or copy the installation files locally. Sometimes we need to update the ISOs (for example, to slipstream a new cumulative update), which we can't do if 30 VMs still have it mounted. So we dismount the ISOs when the installation is done.

Installing from a mapped share instead of a mounted ISO would probably be the sensible approach, though there would be some issues to straighten out relating to permissions and how the installer is invoked. Or we can continue to use the workaround of a DSC script resource to unmount the ISO. Or maybe we should keep the ISO mounted, but temporarily apply a DSC change to unmount the ISO from all VMs any time we want to update it. Fine as long as there aren't too many ISOs to keep mounted!

Still, it sounds like what I need is advice on how to make proper use of DSC, which is off topic in a discussion about a bug fix on a DSC resource. So feel free to leave it at that, or tell me where I might find the answers as to what approach best follows the spirit of DSC!

**Comment by PlagueHO** [comment]
Hi @Peter-B-Clark - Right, I think I understand your use-case here.

It is an interesting scenario. I'm trying to think of an good solution to this problem. 

One of the core ideas behind DSC is that you just define the state of the node that you want and don't need to worry about how DSC makes that happen. Once state has been achieved on a node, DSC should become idempotent (e.g. if it runs again it will change nothing). However, in this case the node will be in state but the DSC config will still make changes.

So all resources are meant to be designed to ensure that DSC Configs are idempotent - however this resource wasn't - which is why we had to fix it.

I guess the best place that summarizes the principals around DSC is the [DSC Documentation](https://msdn.microsoft.com/en-us/powershell/dsc/overview).

Anyway, this is just the intent of DSC, but that doesn't solve your problem here. So I guess what you need is a solution. Would you be able to raise this as a new issue so I can mark it as discussion/question and get a bit more input from around the community?
